version: '3'

services:
  database:
    container_name: 'cf_postgres'
    hostname: 'cf_postgres'
    image: 'postgres:14'
    restart: always
    env_file:
      - ./../.env
    ports:
      - '5432:5432'
